language: node_js
node_js:
- 11.12.0
before_install:
- npm i -g npm@6.11.3
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: stumpie905509@gmail.com
  api_key:
    secure: INzrDekoUHT1xHWY/zlz7e3LbfQHLu614nH5Tv3qmKFAGw4w+xAPhhOx6xObnY4Hb63KK9037/xeCwuYCp0AZmOR7gaSmSj/p88LL3JuUGtPcLFLHB6TbEl7PVWec3C/GLQTN53uqlNgVe//bg2hmzAfzu6I8U6J3GW6WtiaMQG9yxkycqCMNY4rpkZgm+ALpUyG+xMEko/7yuwOkxi+PkCxGtjdQXAv2i+BZ4xZeud7AQ1XzPNsK72gsBorG4OXu6QRg77UvHdP6emjX48BSQCu7L72zyrWt1cIK2FEJdMLGcwNu2ogr4b5jXmWL0T2kS5i9RATXntyY/DVDSRWP5uAxVtLqkYsjEBE1naWd9YNv4Xjgom8hWKWpplZVW3tauXHwjlsNjQ7PXYqufDQXM71Ccomtidksc2v4aZ1mtNPinTX1Q8j+lt0xWx5QrS7Y0h3AkjLooaIy0BjkX5KwqSekfE673QLvb163zaJu6h2Iok//CE1yyFGvNQB9XPDaal5UrFsgvXZvC4+folpEwxHG4t63MwGUAmns4ML4xaZMACTEV7fL4EGCWhip7VNTqkAd5jSeVjn4ZUtvN9dU1pIDed6ab9g02zwq53FPe/NCVDQ2FZTZ58RGlfn6c4yIVSam2n8xiB+M0ZQM+6YA8Qwj6Nfxjl+uzrDFHfgngM=
  on:
    tags: true
    repo: Ztumpie905509/discord-music-wrapper
