language: node_js
node_js:
- 11.12.0
before_install:
- npm i -g npm@6.11.3
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: stumpie905509@gmail.com
  api_key:
    secure: e6csLChq7hEVpFSLAMBaKPVsldkKUtoVHxVnHNn8No60PRa+TRQGAqE09rqLSHFuzGWfRVraJijnQ2I49kVPlXVijMZ9yl5WY5ZcKJsW2bG6YWuflQwEbkbK8zMim6dOtWGKagYN+xGS6GcOK/moySGTiP9jb6r6rFvZgjTtW559JdSDI2Q//xokigu8M2UK3NY9qTaKxq+nvUks8YQ5x7BffW++wCG+CiX0LBCrInmfN1uUY/IaL/Ru8xUyhbEx+TU+KrdVi6TEPtLpVYAj1pEEwyuLFywgrotNNJSJkynbocMmfdl25PRlnrEG8ftGyNNvOUXrh2PfIEm4f0ttVzMoxjVsKbBVNjo3Z+e634FTSYeXN2pXbDkUnOrs1o1vZaF9ILt/th9L0KHh3hWE0fqO3DR7LFr1SK8UfJVrmjlnZUp5BwuAmLn6a5oKFRSnPgcfwRov7TQT6pNghyu2G8ZehZpvfpYMcQK4KaAK4NHeed3TPAhP56CgVgklu/sSywzMm3eWvISQ6cxaEQ7fagiDzd1e7xqa9BdyaB4u7rolkk4oxxvN0C5obVS8LIJl311+C2+RXfQQJ4MpoCz6dy3Uf+geYU8G7shGNWWIPsHwsgODrJgG05Iho4UHtezDyjA+RYtmoWCfQC54+6iMOth419DfIz0CRcLfyk6krfk=
  on:
    tags: true
    repo: Ztumpie905509/discord-music-wrapper
