language: node_js
node_js:
- 11.12.0
before_install:
- npm i -g npm@6.11.3
install:
- npm ci
script:
- npm test
deploy:
  provider: npm
  email: stumpie905509@gmail.com
  api_key:
    secure: O5Fsv3t5r1cJzgCi7teamoGzjp0H+8AzVX2e7X9W6tSFHPuYmO7mHHoVSzw7wB0P7Xg3nIhlDU62r86tLtxM2hUMPs+fH81BfD3VRMojk0Nqhg0hGtGCF7MoNkJ0W0gINSMynwDB/Y8DXL9yxJtIHKqxjTJ3X9mWBN5b9SRwk1S8P68QXU/QMM3maoru9g23etDadajyDKrM8t17ZHPjpv3PLK2vcAFQ0khnJmbIQlzJJbBtLhtN8w++EeWFjnzzW757FrbEZPeqetsT+BPgWiGLKjGr/gVValjKAdL3UZ4Ib6DH2mngutppIWtl4omUzaHfgEjYKI81EK1BtbNgzqtCjAgUxc6RMjy1ela52YG6X8MENwbNrbxwyEC4Zm/oHOIannCbwB4hilK+Hjl264Z5xPhqpcgJhkbWfdcjOljpfEWOzkrTal345q3zfhAE6HLvbNYgIrrcsw+WcOPQhsJ7SPR0ybMKLyjctPIervFoV3d/341rNd51UwuleV3eN2S+Kgbx0ns+YnWv/v+0Z8R01K4iRoBMKpPNiIN9PuTn0pD6aYe/x4vd2T4CKxHS0VTnDkst6S6egEGYDIKxSqL9IjvVpL57AC2/jfKBXf0db8ll6/BNztnx3jOMLIt/dPKPePjS2Gjj+YH+vmjCjPaC8ZWHgeDYEUQ4MTwTbK4=
  on:
    repo: Ztumpie905509/discord-music-wrapper
